version: "3.1"

volumes:
  traefik-ssl-certs:
    driver: local
  portainer_data:

services:
  reverse-proxy:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    restart: unless-stopped
    ports:
      - "80:80" # HTTP
      - 443:443 # HTTPS
      - "8080:8080" # Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./traefik/config:/etc/traefik # Traefik configuration file
      - traefik-ssl-certs:/ssl-certs # SSL certificates

  portainer:
    image: portainer/portainer-ce
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      traefik.enable: "true"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
      traefik.http.services.portainer.loadbalancer.server.scheme: "http"
      traefik.http.routers.portainer-https.entrypoints: "websecure"
      traefik.http.routers.portainer-https.rule: "Host(`portainer.raspberrypi.local`)"
      traefik.http.routers.portainer-https.tls: "true"
      traefik.http.routers.portainer-https.tls.certresolver: "production"
